### ISSUE TITLE
Tables not rendered

### ISSUE THREAD

**Issue by fjudith** [cetra3/md-preview#2]
Hello,

Thanks a lot for this add-on. I was searching a long time for such feature in Alfresco.

Using 1.1.0 amps markdown tables are not rendered using classic markup. 
But works using HTML markup.

### Not working

```
| Firstname | Lastname |
| --------- | -------- |
| Tony      | Stark    |
| Steven    | Rogers   |
```

### Working

```
<table>
<tr><th>Firstname</th><th>Lastname</th></tr>
<tr><td>Tony</td><td>Stark</td></tr>
<tr><td>Steven</td><td>Rogers</td></tr>
</table>
```

May this can be fixed by update showdown.js. But i don't know how to compile amps myself.

**Comment by cetra3** [comment]
Hi @fjudith,

There are instructions on how to compile and generate AMPs in the readme.

Showdown does support tables, but you need to enable it as an option.

You'd need to add `converter.setOption("tables", true)` to the [Markdown Edit's](https://github.com/cetra3/md-preview/blob/master/share/src/main/resources/META-INF/components/markdown-edit.js) Converter object.

**Comment by fjudith** [comment]
Thanks a lot for you quick feedback @cetra3.
I managed to fork your projet and compile AMPs on Windows 10.

ShowdownJS doc says that we can use `converter.setFlavor('github');` which enables a lot of other feature.

I'm going to test this setup and let you know the result

**Comment by fjudith** [comment]
Successfuly tested with `showdown.setFlavor('github');`

I've updated both `Markdown.js` and `markdown.edit.js` by adding the line below `require()` and updated showdown to latest 1.6.3.

This change unlocked Tables, TodoList and many more.

**From showdown.js**
```
    flavor = {
      github: {
        omitExtraWLInCodeBlocks:              true,
        prefixHeaderId:                       'user-content-',
        simplifiedAutoLink:                   true,
        excludeTrailingPunctuationFromURLs:   true,
        literalMidWordUnderscores:            true,
        strikethrough:                        true,
        tables:                               true,
        tablesHeaderId:                       true,
        ghCodeBlocks:                         true,
        tasklists:                            true,
        disableForced4SpacesIndentedSublists: true,
        simpleLineBreaks:                     true,
        requireSpaceBeforeHeadingText:        true,
        ghCompatibleHeaderId:                 true,
        ghMentions:                           true
      },
```

For successful compilation i have commented following lines in `build.gradle` in bothe share and repo directories.

```
    maven {
        credentials {
            //username project['alfresco.repo.private.username']
            //password project['alfresco.repo.private.password']
        }
```

I also changed alfresco.version from `5.0.1` to `5.1.g`.

```
ext {
    alfresco = [:]
    alfresco.version = "5.1.g"
}
```

Thank you !

**Comment by cetra3** [comment]
@fjudith, Happy to accept a PR when you're ready.

**Comment by fjudith** [comment]
@cetra3 PR submitted.
